name: Publish to npm

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install library dependencies
        working-directory: ./watermark-lib
        run: npm install
      
      - name: Build Library
        working-directory: ./watermark-lib
        run: npm run build
      
      - name: Publish to npm
        working-directory: ./watermark-lib
        run: npm publish --provenance --access public
